version: "3.1"
services:

  tests-narfex-redis:
    image: redis:alpine
    container_name: tests-narfex-redis
    ports:
      - "8887:6379"

  tests-narfex-mysql:
    image: mysql:5.6
    container_name: tests-narfex-mysql
    working_dir: /application
    volumes:
      - ../:/application
    environment:
      - MYSQL_ROOT_PASSWORD=adminPass
      - MYSQL_DATABASE=narfex
      - MYSQL_USER=narfex
      - MYSQL_PASSWORD=narfexPass
    ports:
      - "8888:3306"

  tests-narfex-webserver:
    image: nginx:alpine
    container_name: tests-narfex-webserver
    working_dir: /application
    volumes:
      - ../:/application
      - ./phpdocker/nginx/tests.nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8889:80"

  tests-narfex-php-fpm:
    build: phpdocker/php-fpm
    container_name: tests-narfex-php-fpm
    working_dir: /application
    environment:
      - DB_HOST=tests-narfex-mysql
      - DB_NAME=narfex
      - DB_USERNAME=narfex
      - DB_PASSWORD=narfexPass
    volumes:
      - ../:/application
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    ports:
      - "8890:9000"

  tests-narfex-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: tests-narfex-phpmyadmin
    volumes:
      - ./phpdocker/pma/upload.ini:/usr/local/etc/php/php.ini
    environment:
      - PMA_HOST=tests-narfex-mysql
      - PMA_PORT=3306
    depends_on:
      - tests-narfex-mysql
    ports:
      - "8891:80"
    restart: always

  tests-narfex-phpredisadmin:
    image: erikdubbelboer/phpredisadmin
    container_name: tests-narfex-phpredisadmin
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASS=admin
      - REDIS_1_HOST=tests-narfex-redis
      - REDIS_1_PORT=6379
    links:
      - tests-narfex-redis
    ports:
      - "8892:80"
