service: frontend
runtime: nodejs12
instance_class: F1
automatic_scaling:
  max_instances: 1

handlers:
  - url: /static/js/(.*)
    static_files: build/static/js/\1
    upload: build/static/js/(.*)
  - url: /datafeeds/(.*)
    static_files: build/datafeeds/\1
    upload: build/datafeeds/(.*)
  - url: /charting_library/(.*)
    static_files: build/charting_library/\1
    upload: build/charting_library/(.*)
  - url: /static/css/(.*)
    static_files: build/static/css/\1
    upload: build/static/css/(.*)
  - url: /static/media/(.*)
    static_files: build/static/media/\1
    upload: build/static/media/(.*)
  - url: /(.*\.(json|png))$
    static_files: build/\1
    upload: build/.*\.(json|png)$
  - url: /
    static_files: build/index.html
    upload: build/index.html
    secure: always
    redirect_http_response_code: 301
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    secure: always
    redirect_http_response_code: 301
